-- 01_bronze.sql
-- Ingest raw data into Bronze layer

-- Example placeholder:
-- CREATE OR REPLACE TABLE bronze.sales_raw AS
-- SELECT * FROM external_source.sales;

-- Add your data ingestion queries here
USE DATABASE SNOWFLAKE_SAMPLE_DATA;

DESC TABLE TPCDS_SF100TCL.store_sales;
SELECT COUNT(*) 
FROM TPCDS_SF100TCL.STORE_SALES;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE OR REPLACE TABLE BRONZE.STORE_SALES_RAW AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES
LIMIT 50000000;
SELECT COUNT(*) FROM BRONZE.STORE_SALES_RAW;

--PHASE 3 
SELECT COUNT(*) FROM BRONZE.STORE_SALES_RAW;
SELECT COUNT(*) 
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES;

DESC TABLE BRONZE.STORE_SALES_RAW;

SELECT 
COUNT(*) AS TOTAL_ROWS,
COUNT(SS_SALES_PRICE) AS NON_NULL_SALES_PRICE,
FROM BRONZE.STORE_SALES_RAW;

SELECT MIN(ss_sales_price),MAX(ss_sales_price)
from bronze.store_sales_raw;